# Generated by Django 5.2.6 on 2025-10-20 08:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_skillembedding'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopicEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255, unique=True)),
                ('embedding', models.BinaryField()),
                ('source', models.CharField(default='MANUAL', max_length=100)),
                ('model_name', models.CharField(default='all-mpnet-base-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterField(
            model_name='extractedskill',
            name='embedding_model',
            field=models.CharField(default='all-mpnet-base-v2', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillembedding',
            name='model_name',
            field=models.CharField(default='all-mpnet-base-v2', max_length=100),
        ),
        migrations.CreateModel(
            name='ClassifiedTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('embedding_model', models.CharField(default='all-mpnet-base-v2', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_topics', to='api.paper')),
            ],
            options={
                'unique_together': {('paper', 'topic_name', 'embedding_model')},
            },
        ),
    ]
