# Generated by Django 5.2.6 on 2025-10-27 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_topicembedding_alter_extractedskill_embedding_model_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classifiedtopic',
            name='embedding_model',
            field=models.CharField(default='allenai/specter2_base', max_length=255),
        ),
        migrations.AlterField(
            model_name='extractedskill',
            name='embedding_model',
            field=models.CharField(default='allenai/specter2_base', max_length=255),
        ),
        migrations.AlterField(
            model_name='skillembedding',
            name='model_name',
            field=models.CharField(default='allenai/specter2_base', max_length=100),
        ),
        migrations.AlterField(
            model_name='topicembedding',
            name='model_name',
            field=models.CharField(default='allenai/specter2_base', max_length=100),
        ),
    ]
