# Generated by Django 5.2.6 on 2025-10-29 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_remove_classifiedtopic_confidence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topicembedding',
            name='topic_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='topicembedding',
            unique_together={('topic_name', 'source', 'model_name')},
        ),
    ]
