# Generated by Django 5.2.6 on 2025-11-15 07:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_rename_classifiedtopic_extractedskill_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255)),
                ('embedding', models.BinaryField()),
                ('source', models.CharField(default='MANUAL', max_length=100)),
                ('model_name', models.CharField(default='all-mpnet-base-v2', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('skill_name', 'source', 'model_name')},
            },
        ),
        migrations.DeleteModel(
            name='TopicEmbedding',
        ),
        migrations.RenameField(
            model_name='extractedskill',
            old_name='level_0_topic',
            new_name='level_0_skill',
        ),
        migrations.RenameField(
            model_name='extractedskill',
            old_name='topic_name',
            new_name='skill_name',
        ),
        migrations.RenameField(
            model_name='extractedsubskill',
            old_name='topic_name',
            new_name='skill_name',
        ),
        migrations.AlterUniqueTogether(
            name='extractedskill',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='extractedskill',
            name='embedding_model',
            field=models.CharField(default='all-mpnet-base-v2', max_length=255),
        ),
        migrations.AlterField(
            model_name='extractedskill',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_skills', to='api.paper'),
        ),
        migrations.AlterField(
            model_name='extractedsubskill',
            name='paper',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_sub_skillss', to='api.paper'),
        ),
        migrations.AlterUniqueTogether(
            name='extractedskill',
            unique_together={('paper', 'skill_name', 'embedding_model')},
        ),
    ]
