# Generated by Django 5.2.9 on 2026-01-06 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_skillembedding_delete_topicembedding_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('openalex_id', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('institution', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='paper',
            name='authors_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='paper',
            name='authors',
        ),
        migrations.AddField(
            model_name='paper',
            name='authors',
            field=models.ManyToManyField(related_name='papers', to='api.author'),
        ),
    ]
