# Generated by Django 5.2.9 on 2026-01-18 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_author_paper_authors_text_remove_paper_authors_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='cluster_id',
            field=models.IntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='cluster_label',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
