# Generated by Django 5.2.9 on 2026-01-20 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_paper_cluster_id_paper_cluster_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='primary_cluster',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
