# Generated by Django 5.2.9 on 2026-01-27 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_author_faculty'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='dapartment',
            new_name='department',
        ),
    ]
