# Generated by Django 5.2.9 on 2026-03-18 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_alter_extractedskill_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='predicted_multi_labels',
            field=models.JSONField(blank=True, help_text='List of predicted labels', null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='department',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
