# Generated by Django 5.2.9 on 2026-03-19 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_paper_predicted_multi_labels_alter_author_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='last_fetched_papers',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(default='Thammasat University', max_length=255),
        ),
    ]
