# Generated by Django 5.2.9 on 2026-03-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_paper_topic_keywords'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='institution',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
