# Generated by Django 5.2.6 on 2025-10-13 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_extractedskill'),
    ]

    operations = [
        migrations.CreateModel(
            name='SkillEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=255, unique=True)),
                ('embedding', models.BinaryField()),
                ('source', models.CharField(default='ESCO', max_length=100)),
                ('model_name', models.CharField(default='allenai/specter2_base', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
