# Generated by Django 5.2.6 on 2025-10-27 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_classifiedtopic_embedding_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classifiedtopic',
            name='confidence',
        ),
        migrations.AddField(
            model_name='classifiedtopic',
            name='level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='classifiedtopic',
            name='vote_count',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='ClassifiedSubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic_name', models.CharField(max_length=255)),
                ('confidence', models.FloatField(default=0.0)),
                ('source_sentence', models.TextField(blank=True, null=True)),
                ('embedding_model', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classified_sub_topics', to='api.paper')),
            ],
        ),
    ]
