# Generated by Django 5.2.6 on 2025-10-30 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_alter_topicembedding_topic_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='classifiedtopic',
            name='level_0_topic',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
