# Generated by Django 5.2.6 on 2025-11-04 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_classifiedtopic_level_0_topic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='extractedskill',
            name='paper',
        ),
        migrations.DeleteModel(
            name='SkillEmbedding',
        ),
        migrations.DeleteModel(
            name='ExtractedSkill',
        ),
    ]
