# Generated by Django 5.2.6 on 2025-11-15 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_extractedskill_paper_delete_skillembedding_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClassifiedTopic',
            new_name='ExtractedSkill',
        ),
        migrations.RenameModel(
            old_name='ClassifiedSubTopic',
            new_name='ExtractedSubSkill',
        ),
    ]
