# Generated by Django 5.2.9 on 2026-01-27 06:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_author_primary_cluster'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='dapartment',
            field=models.CharField(blank=True, max_length=266, null=True),
        ),
    ]
