# Generated by Django 5.2.9 on 2026-01-27 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_author_dapartment'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='faculty',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
