# Generated by Django 5.2.9 on 2026-01-30 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_dapartment_author_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='topic_profile',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='topic_distribution',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
