# Generated by Django 5.2.9 on 2026-02-08 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_author_topic_profile_paper_topic_distribution'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='entropy',
            field=models.FloatField(blank=True, db_index=True, null=True),
        ),
    ]
