# Generated by Django 5.2.9 on 2026-02-11 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_paper_entropy'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='openalex_concepts',
            field=models.JSONField(blank=True, help_text='List of concepts from OpenAlex', null=True),
        ),
    ]
