# Generated by Django 5.2.9 on 2026-03-16 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_paper_openalex_concepts'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='extractedskill',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='extractedskill',
            name='paper',
        ),
        migrations.RemoveField(
            model_name='extractedsubskill',
            name='paper',
        ),
        migrations.DeleteModel(
            name='SkillEmbedding',
        ),
        migrations.DeleteModel(
            name='ExtractedSkill',
        ),
        migrations.DeleteModel(
            name='ExtractedSubSkill',
        ),
    ]
