# Generated by Django 5.2.9 on 2026-03-19 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_author_email_author_last_fetched_papers_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='topic_keywords',
            field=models.JSONField(blank=True, help_text='Raw keywords from BERTopic', null=True),
        ),
    ]
